### ISSUE TITLE
How to change the mode of ArcSoft SDK?

### ISSUE THREAD

**Issue by artzers** [TuYuxiao/face_recognize#1]
Hello. There are 2 modes for ArcSoft SDK when using initEngine(), namely video(0x00000000) and image(0xFFFFFFFF). How to change the mode in this python package ? Thanks.

**Comment by TuYuxiao** [comment]
Because some face detection backends have no acceleration for video, there is no method to explicitly change the mode in FaceDetector and ther is no need to care about the mode in normal usage. If you call _detect_ method, the image mode engine would be used. If you call _track_ method, the video mode engine would be used. If you insist on changing the engine mode called by FaceDetector, you can change the source code or directly call the low level backend methods.
